version: "3"
services:
  service:
    tty: true
    container_name: ca-service
    build:
      context: ./service
    command: ["yarn", "build"]
    volumes:
      - ./service:/usr/src/app:cached
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=local
      - OPTIMIZED_BUILD=false
      - PORT=5000
      - AWS_REGION=eu-central-1
      - DYNAMO_ENDPOINT=http://database:8000/db
  app:
    tty: true
    container_name: ca-app
    build:
      context: ./app
    command: ["yarn", "start"]
    volumes:
      - ./app:/usr/src/app:cached
    ports:
      - 4040:4040
      # live reload server port
      - 35729:35729
    environment:
      - NODE_ENV=local
      - OPTIMIZED_BUILD=false
      - PORT=4040
    depends_on:
      - service
