import {
  getGame,
  postGame,
  putGamePlayer,
  getGamePlayer,
  putAnswer,
  patchRevealQuestion,
  patchRevealAnswers,
  postWinningAnswer,
  getCurrentRound,
  putNewRound,
  getAnswer,
  patchPlayerActive,
  patchPlayerInactive,
  deleteGamePlayer,
} from "./controller";

export {
  getGame,
  postGame,
  putGamePlayer,
  getGamePlayer,
  putAnswer,
  patchRevealQuestion,
  patchRevealAnswers,
  postWinningAnswer,
  getCurrentRound,
  putNewRound,
  getAnswer,
  patchPlayerActive,
  patchPlayerInactive,
  deleteGamePlayer,
};
