on:
  push:
    branches:
      - master

name: Deploy service to AWS ECS

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        working-directory: ./service
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: coathanger-abortions-service
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container
          docker build --no-cache \
          --build-arg OPTIMIZED_BUILD=true \
          --build-arg NODE_ENV=production \
          --build-arg AWS_REGION=eu-central-1 \
          --build-arg PORT=8080 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # push it to ECR so that it can
          # be deployed to ECS.
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:latest"

      - name: Update and deploy Amazon ECS task definition
        id: deploy-task-def
        working-directory: ./service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          DOCKER_IMAGE_URL: ${{ steps.build-image.outputs.image }}
        run: |
          # Deploy the new docker image by updating
          # the task definition of the service
          bash ecs_deploy.sh \
          --aws-access-key $AWS_ACCESS_KEY_ID \
          --aws-secret-key $AWS_SECRET_ACCESS_KEY \
          --cluster coathanger-abortions-service  \
          --service-name coathanger-abortions-service-service \
          --image $DOCKER_IMAGE_URL \
          --region $AWS_DEFAULT_REGION \
          --timeout 240 \
          --max-definitions 5 \
          --enable-rollback \
          --skip-deployments-check
